config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[new create show index]
  resources :groups, only: %i[new create show index]
  resources :hours, only: %i[new create show index] do
    collection do
      get 'externalhours'
    end
  end
  resources :sessions, only: %i[new create destroy]
  get '/signup', to: 'users#new'
  get '/logout', to: 'sessions#destroy'
  get '/signin', to: 'sessions#new'
  root 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, length: { maximum: 40 }

  belongs_to :user, dependent: :destroy
  has_many :grouphours, dependent: :destroy
  has_many :hours, through: :grouphours, source: :hour
  has_one_attached :icon
  has_many_attached :uploads
end

public
def grouptotalhours(group)
  group.hours.sum(:hours)
end

app/models/grouphour.rb
class Grouphour < ApplicationRecord
  belongs_to :hour
  belongs_to :group
end

app/models/hour.rb
class Hour < ApplicationRecord
  has_many_attached :uploads
  validates :hours, presence: true, numericality: { only_integer: true }

  has_many :grouphours, dependent: :destroy
  has_many :groups, through: :grouphours, source: :group
  belongs_to :user, dependent: :destroy
end

public

def totalhours(user)
  user.hours.sum(:hours)
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20 }

  has_many :hours, dependent: :destroy
  has_many :groups, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :login_required

  def login_required
    unless logged_in?
      flash.now[:notice] = 'You are not logged in, please do so or signup'
      redirect_to new_session_path
    end
  end

  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  def current_user
    if session[:user_id]
      @current_user = User.find_by_id(session[:user_id])
      @current_user || false
    else
      false
    end
  end
  helper_method :current_user
end

app/controllers/grouphours_controller.rb
class GrouphoursController < ApplicationController
  def index
    @grouphours = Grouphours.all
  end

  def new
    @grouphour = current_user.grouphour.build
  end

  def create
    @grouphour = current_user.grouphour.build(grouphour_params)
    if @grouphour.save
      flash.now[:succes] = 'Hour successful created'
      redirect_to @grouphour
    else
      render :new
    end
  end

  def show
    @grouphour = Grouphour.find_by_id([:hour_id])
  end

  private

  def grouphour_params
    params.require(:grouphour).permit(:group_id, :hour_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.includes(:hours).all
    @group = Group.includes(:hours).find_by_id(params[:id])
  end

  def new
    @group = current_user.groups.build
  end

  def create
    @group = current_user.groups.build(group_params)
    Rails.logger.info group_params
    if @group.save
      flash.now[:succes] = 'Group successful created'
      redirect_to @group
    else
      render :new
    end
  end

  def show
    @groups = Group.includes(:hours).all.order(:name)
    @group = Group.includes(:hours).find_by_id(params[:id])
    @hours = Hour.includes(:groups).all
    @grouphours = @group.hours
    @user = User.includes(:groups).find_by_id(params[:id])
    @grouphourscount = @group.hours.grouptotalhours(@group)
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon, :user_id, uploads: [])
  end
end

app/controllers/hours_controller.rb
class HoursController < ApplicationController
  before_action :login_required, only: %i[new create]

  def index
    @hours = current_user.hours.includes(:groups).all.order(created_at: :desc)
  end

  def new
    @hour = Hour.new
  end

  def create
    @hour = current_user.hours.build(hour_params)
    @hour.save
    if @hour.save
      flash.now[:succes] = 'Hour successful created'
      redirect_to hour_path(@hour)
    else
      render :new
    end
  end

  def show
    @hours = current_user.hours.includes(:groups).all.order(created_at: :desc)
    @hour = Hour.find_by_id(params[:id])
    @users = User.includes(:hours).all
    @user = User.includes(:hours).find_by_id(params[:id])
    @groups = Group.includes(:hours, :users).all
    @count = Hour.includes(:users).totalhours(current_user)
  end

  def externalhours
    @externalhours = []
    current_user.hours.each do |hour|
      @externalhours.push hour if hour.groups.count.zero?
    end
    @sorted = @externalhours.sort_by(&:created_at)
  end

  private

  def hour_params
    params.require(:hour).permit(:hours, :description, :user_id, :group_id, group_ids: [], uploads: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: %i[new create]
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_name(params[:name])
    if User.exists?(@user.id)
      session[:user_id] = @user.id
      redirect_to root_path
    elsif @user != User.any?(:name)
      @new_user = User.new(params)
      @new_user.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_user_path
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  private

  def login(_user)
    session[:user_id] = nil
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[new create]
  def index
    @users = User.includes(:hours).all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    if @user.save
      flash.now[:succes] = 'User has been successfully added'
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find_by_id([:user_id])
    @user_hours = current_user.hours.all
    @user_groups = current_user.groups.all
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header
    if logged_in?
      concat link_to 'Logout', logout_path
      concat link_to 'Back to Profile', root_path
      link_to 'Add a new hour(s)', new_hour_path
    else
      concat link_to 'Login', signin_path
      link_to 'Sign Up', new_user_path
    end
  end
end

app/helpers/grouphours_helper.rb
module GrouphoursHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def attached
    @groups.each do |group|
      concat image_tag(group.icon.variant(resize: '200 x 200')) if group.icon.attached?
    end
  end

  def uploads
    @group.uploads.each do |upload|
      if upload.variable?
        concat image_tag(upload.variant(resize: '400 x 400'))
      elsif upload.previewable?
        concat link_to image_tag(resize.uploads.preview('400 x 400'), upload)
      elsif upload.image?
        concat link_to image_tag(resize.uploads.preview('400 x 400'), upload)
      end
    end
  end

  def attachment
    image_tag(@group.icon.variant(resize: '200 x 200')) if @group.icon.attached?
  end
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<div class="logo">

</div>
<div class="header-hours">
    <div class="image"> <i class="fa fa-bars" aria-hidden="true"></i></div>
    <div class="image"> ALL GROUPS </div>
    <div class="image"> <i class="fa fa-search" aria-hidden="true"></i></div>
</div> <br> <br>
<div class="header-hou">
    <div class="image"></div>
    <div class="image"> Most Recent </div>
    <div class="image"> Most Acient</i></div>
</div>
<% @groups.each do |group|%>
    <div class="single-item">
        <div class="descriptionh">
            <%= link_to group.name, group_path(group) %>
        </div>
        <div class="description">
            <% attached %>
        </div>
        <div class="descriptionh">
            <%= group.created_at %> &nbsp
        </div>
    </div>
<% end %> </p>

<p>
<%= link_to '<button type="button">New Group</button>'.html_safe, new_group_path %>
</p>

app/views/groups/new.html.erb
<%= form_for @group do |form|%> <br> <br>
  <%= form.hidden_field :user, :value => current_user.name %>
    <%= form.label :name %> <br>
    <%= form.text_field :name %> <br> <br>
    <%= form.label :icon %> <br>
    <%= form.file_field :icon %> <br> <br>
    <%= form.label :uploads %> <br>
    <%= form.file_field :uploads, multiple: true %><br><br>
    <%= form.submit %>
<% end %>

app/views/groups/show.html.erb
<div class="group-title">
    <h1> <%= @group.name %> </h1>
</div
<div class ="profile-items">
            <%= attachment %>

    <% @grouphours.each do |hour|%>
        <%= hour.hours %>
    <% end %>
    <p>
    Created at:    <%= @group.created_at %>
    </p>

    <p>
    Authoured by:    <%= @user.name %>
    </p>
    <%= @group.uploads.count %>

        <% uploads %>

<div>

<br>
<div class="header-hours">
    <div class="image"> <i class="fa fa-bars" aria-hidden="true"></i></div>
    <div class="image"> THE GROUP HOURS </div>
    <div class="image"> <i class="fa fa-search" aria-hidden="true"></i></div>
</div> <br> <br>
<div class="header-hou">
    <div class="image"></div>
    <div class="image"> Most Recent </div>
    <div class="image"> Most Acient</i></div>
</div>
<div class="contenth">
    <div class="count"> 
        <div class="totalhours">
        Total hours
        </div>
        <div class="number">  <%= @grouphourscount %>hrs </div>
    </div>
    <div class="singleitemblock">
        <% @grouphours.each do |hour| %>
            <div class="single-item">
                <div class="descriptionh">
                    <%= hour.description %>
                </div>
                <div class="descriptionh">
                    <%= hour.hours %> hrs
                </div>
            </div>
            <div class="time">
                <%= hour.created_at %>
            </div><br>
            <div class="time">
                <%= hour.created_at %>
            </div><br>
            <div class="time">
                Authoured by: <%= @user.name %>
            </div><br>
        <% end %>
    </div>

    <br><br>
    <div class="button">
        <div class="layout">
            <%= link_to 'Add new', new_hour_path %>
        </div>
    </div>
</div>

app/views/hours/externalhours.html.erb
<h1>  </h1>
<br>
<div class="header-hours">
    <div class="image"> <i class="fa fa-bars" aria-hidden="true"></i></div>
    <div class="image"> User external hours </div>
    <div class="image"> <i class="fa fa-search" aria-hidden="true"></i></div>
</div> <br> <br>
<div class="header-hou">
    <div class="image"></div>
    <div class="image"> Most Recent </div>
    <div class="image"> Most Acient</i></div>
</div>
<div class="contenth">
    <div class="externalhrs">
        <% @sorted.each do |hour|%>
        <div class="single-item">
            <div class="descriptionh">
                <%= hour.description %>
            </div>
            <div class="descriptionh">
                <%= hour.hours %> hrs
            </div>
        </div>
        <div class="time">
                    <p><%= hour.created_at %> </p>
        </div><br>

        <% end %>
</div>
    <div class="button">
        <div class="layout">
            <%= link_to 'Add new', new_hour_path %>
        </div>
    </div>
</div>

app/views/hours/index.html.erb
<br>
<div class="header-hours">
    <div class="image"> <i class="fa fa-bars" aria-hidden="true"></i></div> <br>
    <div class="image"> <br> <%= "All #{current_user.name}\'s hours" %> </div>
    <div class="image"> <i class="fa fa-search" aria-hidden="true"></i></div>
</div> <br> <br>
<div class="header-hou">
    <div class="image"></div>
    <div class="image"> Most Recent </div>
    <div class="image"> Most Acient</i></div>
</div>
<div class="contenth">
    <div class="externalhrs">
        <% @hours.each do |hour|%>
        <div class="single-item">
            <div class="descriptionh">
                <%= hour.description %>
            </div>
            <div class="descriptionh">
                <%= hour.hours %> hrs
            </div>
        </div>
        <div class="time">
                    <p><%= hour.created_at %> </p>
        </div><br>

        <% end %>
</div>
    <div class="button">
        <div class="layout">
            <%= link_to 'Add new', new_hour_path %>
        </div>
    </div>
</div>

app/views/hours/new.html.erb
<div class="hourf">
    <%= form_for @hour do |form|%><br><br>
        <%= form.hidden_field :user, :value => current_user.name %>
        <%= form.label :hours %> <br>
        <%= form.text_field :hours %><br><br>
        <%= form.label :description %><br>
        <%= form.text_area :description %><br><br>
        <%= form.label  :uploads %> <br>
        <%= form.file_field :uploads, multiple: true %> <br><br>
        <div class="dropdown">
            Select a group <%= form.collection_select :group_ids, Group.all, :id, :name, { prompt: "select a group" }, { multiple: true } %> <br><br>
        </div>
        <%= form.submit %><br><br>
    <% end %>
</div>

app/views/hours/show.html.erb
<br>
<div class="header-hours">
    <div class="image"> <i class="fa fa-bars" aria-hidden="true"></i></div>
    <div class="image"> THE HOURS </div>
    <div class="image"> <i class="fa fa-search" aria-hidden="true"></i></div>
</div> <br> <br>
<div class="header-hou">
    <div class="image"></div>
    <div class="image"> Most Recent </div>
    <div class="image"> Most Acient</i></div>
</div>
<div class="contenth">
    <div class="count"> 
        <div class="totalhours">
        Total hours
        </div>
        <div class="number"> <%= @count %> hrs </div>
    </div>
    <div class="singleitemblock">
        <% @hours.each do |hour| %>
        <div class="single-item">
            <div class="descriptionh">
                <%= hour.description %>
            </div>
            <div class="descriptionh">
                <%= hour.hours %> hrs
            </div>
        </div>
        <div class="time">
                    <p><%= hour.created_at %> </p>
        </div><br>
                <% end %>
    </div>

    <br><br>
    <div class="button">
        <div class="layout">
            <%= link_to 'Add new', new_hour_path %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupHours</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

  <body>
    <%= header %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1> SignUp </h1></h1> <br> <br><br> <br><br> <br>
<div class="session">
    <%= form_for @user do |form| %>
        <%= form.label :name %><br>
        <%= form.text_field :name %><br><br>
        <%= form.submit :SignUp %>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="profile-title">
    <h1> <%= "#{current_user.name.capitalize }\'s Profile" %></h1> <br> <br>
</div>
<div class="profile-body">
    <div class="motherdiv1">
        <div class="circle">
            <i class="fa fa-cog awesome-icon" aria-hidden="true"></i>
        </div>
        <div class="list-names">
            <div class="subtitle">
                <h4> <%= link_to 'All my hours', hours_path %></h4> <br>
                <hr>
            </div>
            <div class="content">
                <ul>
                    <% @user_hours.each do |uh| %>
                        <li> <%= link_to uh.hours, hour_path(uh) %> &nbsp hrs
                        <%= link_to uh.description, hour_path(uh)%> </li>
                    <% end %>
                </ul>
            </div>
        <div>
    </div>
    <div class="motherdiv2">
        <div class="circle">
            <i class="fa fa-cog awesome-icon" aria-hidden="true"></i>
        </div>
        <div class="mother-lists2">
            <h4> <%= link_to 'All my external hours', externalhours_hours_path %> </h4> <br>
        <hr>
        </div>
    </div>
    <div class="motherdiv3">
        <div class="circle">
            <i class="fa fa-cog awesome-icon" aria-hidden="true"></i>
        </div>
        <div class="list-names">
            <div class="list-subtitle">
                <h4> <%= link_to 'All Groups', groups_path %> </h4> <br>
                <div class="list-content">
                    <ul>
                        <% @user_groups.each do |group| %>
                            <li> <%= link_to group.name, group_path(group) %> </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>